<h1>Login</h1>

<?php 
	//Embora esteja sendo feito no arquivo de view poderias ser feito no arquivo de form

	$username = $form->get('username');
	$username->setAttribute('class', 'form-control')
		->setLabelAttributes(['class' => 'control-label']);

	$password = $form->get('password');
	$password->setAttribute('class', 'form-control')
		->setLabelAttributes(['class' => 'control-label']);

	$submit = $form->get('submit');
	$submit->setAttribute('class', 'btn btn-primary');

	$form->setAttribute('action', $this->url('login'));
	$form->prepare();
?>	

<?php if($messageError): ?>
	<div class="alert alert-danger alert-dismissable" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&lines;</span>
		</button>
		<strong>Erro!</strong> <?= $messageError ?>
	</div>
<?php endif; ?>

<div class="row">
	<div class="col-md-6">
		<?= $this->form()->openTag($form); ?>

		<div class="form-group">
			<?= $this->formLabel($username); ?>
			<?= $this->formElement($username); ?>
		</div>

		<div class="form-group">
			<?= $this->formLabel($password); ?>
			<?= $this->formElement($password); ?>
		</div>

		<?php
		echo $this->formSubmit($submit);
		echo $this->form()->closeTag();
		?>
	</div>
</div>