<h1>Add new Post</h1>

<?php 
	//Embora esteja sendo feito no arquivo de view poderias ser feito no arquivo de form

	$title = $form->get('title');
	$title->setAttribute('class', 'form-control')
		->setLabelAttributes(['class' => 'control-label']);

	$content = $form->get('content');
	$content->setAttribute('class', 'form-control')
		->setLabelAttributes(['class' => 'control-label']);

	$submit = $form->get('submit');
	$submit->setAttribute('class', 'btn btn-primary');

	$form->setAttribute('action', $this->url('admin-blog/blog', ['action'=>'add']));
	$form->prepare();

	echo $this->form()->openTag($form);
?>	

<?php $message = $this->formElementErrors($title, ['class' => 'help-block']); ?>
<div class="form-group<?= $message ? " has-error" : ""?>">
	<?= $this->formLabel($title); ?>
	<?= $this->formElement($title); ?>
	<?= $message; ?>
</div>

<?php $message = $this->formElementErrors($content, ['class' => 'help-block']); ?>
<div class="form-group<?= $message ? " has-error" : ""?>">
	<?= $this->formLabel($content); ?>
	<?= $this->formElement($content); ?>
	<?= $this->formElementErrors($content, ['class' => 'help-block']); ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();
?>