<?php

namespace CHROCKS\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use CHROCKS\Repositories\UserRepository;
use CHROCKS\Models\User;
use CHROCKS\Validators\UserValidator;

/**
 * Class UserRepositoryEloquent
 * @package namespace CHROCKS\Repositories;
 */
class UserRepositoryEloquent extends BaseRepository implements UserRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return User::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function create(array $attributes)
    {
        $attributes['password'] = bcrypt($attributes['password']);
        parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
